//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitCoinRhNetwork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitCoinRhNetwork.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BitCoin address already exists..
        /// </summary>
        public static string AirDrop_Error_AddressAlreadyExists {
            get {
                return ResourceManager.GetString("AirDrop_Error_AddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid BitCoin address submitted..
        /// </summary>
        public static string AirDrop_Error_WrongAddress {
            get {
                return ResourceManager.GetString("AirDrop_Error_WrongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid email submitted..
        /// </summary>
        public static string AirDrop_Error_WrongEmail {
            get {
                return ResourceManager.GetString("AirDrop_Error_WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid signature submitted..
        /// </summary>
        public static string AirDrop_Error_WrongSignature {
            get {
                return ResourceManager.GetString("AirDrop_Error_WrongSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2017 DutyEx.com.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs during saving your avatar.
        /// </summary>
        public static string Error_SaveAvatarToDisk {
            get {
                return ResourceManager.GetString("Error_SaveAvatarToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs during saving your image.
        /// </summary>
        public static string Error_SaveImageToDisk {
            get {
                return ResourceManager.GetString("Error_SaveImageToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Extension.
        /// </summary>
        public static string Error_WrongExtension {
            get {
                return ResourceManager.GetString("Error_WrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id_Label {
            get {
                return ResourceManager.GetString("Id_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string IsPublished_Label {
            get {
                return ResourceManager.GetString("IsPublished_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you winner?.
        /// </summary>
        public static string IsWinner_Label {
            get {
                return ResourceManager.GetString("IsWinner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončení registrace přes sociální síť.
        /// </summary>
        public static string Login_FinalizeExternalLogin {
            get {
                return ResourceManager.GetString("Login_FinalizeExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error: no valid data. Please try again..
        /// </summary>
        public static string LoginError_NoValidToken {
            get {
                return ResourceManager.GetString("LoginError_NoValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení přes sociální síť se nezdařilo. Zkuste to prosím znovu..
        /// </summary>
        public static string LoginError_ProviderUnConfirm {
            get {
                return ResourceManager.GetString("LoginError_ProviderUnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or.
        /// </summary>
        public static string LoginOr {
            get {
                return ResourceManager.GetString("LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Password.
        /// </summary>
        public static string LostPassword {
            get {
                return ResourceManager.GetString("LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password.
        /// </summary>
        public static string LostPassword_BtnSendMail {
            get {
                return ResourceManager.GetString("LostPassword_BtnSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you lost your password, send it to your email entered below.
        /// </summary>
        public static string LostPassword_Content {
            get {
                return ResourceManager.GetString("LostPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string LostPassword_EmailDoesntExist {
            get {
                return ResourceManager.GetString("LostPassword_EmailDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitCoinRhNetwork - Lost password.
        /// </summary>
        public static string LostPassword_EmailSubject {
            get {
                return ResourceManager.GetString("LostPassword_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was sent..
        /// </summary>
        public static string LostPassword_MailSended {
            get {
                return ResourceManager.GetString("LostPassword_MailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your temporary new password is: {0}&lt;br&gt;Please change it after your login!&lt;br&gt;&lt;br&gt;BitCoinRhNetwork&lt;br&gt;https://www.BitCoinRhNetwork.com.
        /// </summary>
        public static string LostPassword_NewTemporary {
            get {
                return ResourceManager.GetString("LostPassword_NewTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was sent to provided email..
        /// </summary>
        public static string LostPassword_PasswordSended {
            get {
                return ResourceManager.GetString("LostPassword_PasswordSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost password.
        /// </summary>
        public static string PageTitle_LostPasswordIndex {
            get {
                return ResourceManager.GetString("PageTitle_LostPasswordIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sign up.
        /// </summary>
        public static string PageTitle_RegisterIndex {
            get {
                return ResourceManager.GetString("PageTitle_RegisterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category.
        /// </summary>
        public static string ParentCategory_Empty_Field {
            get {
                return ResourceManager.GetString("ParentCategory_Empty_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        public static string ParentCategory_Label {
            get {
                return ResourceManager.GetString("ParentCategory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string Placeholder_email {
            get {
                return ResourceManager.GetString("Placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Placeholder_password {
            get {
                return ResourceManager.GetString("Placeholder_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been updated.
        /// </summary>
        public static string Profile_Updated {
            get {
                return ResourceManager.GetString("Profile_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been updated.
        /// </summary>
        public static string ProfilePassword_Updated {
            get {
                return ResourceManager.GetString("ProfilePassword_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity_Label {
            get {
                return ResourceManager.GetString("Quantity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Register_BtnSend {
            get {
                return ResourceManager.GetString("Register_BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty data was entered..
        /// </summary>
        public static string Registration_Error_EmptyForm {
            get {
                return ResourceManager.GetString("Registration_Error_EmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is invalid..
        /// </summary>
        public static string Registration_Error_Invalid {
            get {
                return ResourceManager.GetString("Registration_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords arent identical..
        /// </summary>
        public static string Registration_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Registration_Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with this user name already exists..
        /// </summary>
        public static string Registration_Error_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Registration_Error_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with this email already exists..
        /// </summary>
        public static string Registration_Error_UserEmailAlreadyExists {
            get {
                return ResourceManager.GetString("Registration_Error_UserEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is too short. Try longer..
        /// </summary>
        public static string Registration_Error_UserNameTooShort {
            get {
                return ResourceManager.GetString("Registration_Error_UserNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid email submitted..
        /// </summary>
        public static string Registration_Error_WrongEmail {
            get {
                return ResourceManager.GetString("Registration_Error_WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populární odkazy.
        /// </summary>
        public static string Tags_Title {
            get {
                return ResourceManager.GetString("Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text_Label {
            get {
                return ResourceManager.GetString("Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Title_Label {
            get {
                return ResourceManager.GetString("Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Url_Label {
            get {
                return ResourceManager.GetString("Url_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string User_Avatar_Label {
            get {
                return ResourceManager.GetString("User_Avatar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string User_Edit_Title {
            get {
                return ResourceManager.GetString("User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string User_Email_Label {
            get {
                return ResourceManager.GetString("User_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous user.
        /// </summary>
        public static string User_Empty_Field {
            get {
                return ResourceManager.GetString("User_Empty_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string User_FirstName_Label {
            get {
                return ResourceManager.GetString("User_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User_Label {
            get {
                return ResourceManager.GetString("User_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string User_Language_Label {
            get {
                return ResourceManager.GetString("User_Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string User_LastName_Label {
            get {
                return ResourceManager.GetString("User_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string User_New_Title {
            get {
                return ResourceManager.GetString("User_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password_Label {
            get {
                return ResourceManager.GetString("User_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Verify.
        /// </summary>
        public static string User_PasswordVerify_Label {
            get {
                return ResourceManager.GetString("User_PasswordVerify_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string User_Phone_Label {
            get {
                return ResourceManager.GetString("User_Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string User_Role_Label {
            get {
                return ResourceManager.GetString("User_Role_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string User_UserName_Label {
            get {
                return ResourceManager.GetString("User_UserName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value_Label {
            get {
                return ResourceManager.GetString("Value_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEx.
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube link.
        /// </summary>
        public static string YouTubeUrl_Label {
            get {
                return ResourceManager.GetString("YouTubeUrl_Label", resourceCulture);
            }
        }
    }
}
